import Head from 'next/head';
import { useEffect } from 'react';
import { Typography, makeStyles, Container, Link, Box } from '@material-ui/core';
import { SwipeableStepper } from '../../components/cards/carousel/carousel.component';

const useStyles = makeStyles({
    overlay: {
      boxShadow: 'rgba(0, 0, 0, .5) 0 0 0 1000000px inset',
      margin: '0 !important',
    },
    box: {
        paddingTop: '20px',
        background: 'white',
        width: '100%',
        padding: 0,
        '@media (min-width: 1080px)' : {
          width: '75%',
          alignItems: 'center',
        }
    },
    text: {
        paddingTop: '20px',
        paddingRight: '20px',
        paddingLeft: '20px',
        fontSize: '18px',
        lineHeight: '20px',
        fontWeight: 300,
        paddingBottom: '20px',
    },
    sectionHeader: {
        fontSize: '24px',
        fontWeight: 500,
        padding: '0.7rem',
        borderTop: '1px solid black',
        borderBottom: '1px solid black',
        textAlign: 'center',
    },
    openSpaceContainer: {
        background: 'white',
        width: '100%',
        paddingTop: '20px',
        paddingBottom: '20px',
    },
    image: {
        height: 'fit-content',
        width: '100%',
    }
  });
  
  function srcset(image: string) {
    return {
      src: `${image}`,
    };
  }

export default function OpenSpacePage() {

  useEffect(()=> {
    localStorage.setItem("EsseCurentPageName", "open-space");
  })
  
  const classes = useStyles();

  return (
    <>
        <Head>
            <title>Open Space</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="canonical" href="https://esse-jazz-don.ru/contacts"/>
            <meta name="theme-color" content="#1a1a1a"/>
            <link rel="icon" href="/favicon.ico" />
            <link rel="manifest" href="/manifest.json"/>
        </Head>
    <Container className={ classes.box}>
        <Typography variant='h4' className={ classes.sectionHeader }>
            Open Space
        </Typography>
        <Typography variant='body2' className={ classes.text }>
            Эссе это не только концертная площадка, но и открытое пространство.<br/><br/>
            Мы готовы предоставить клуб для вашего бизнес-завтрака, презентации или лекции.
        </Typography>
        <SwipeableStepper>
              { 
                images.map((item) => 

                  <img
                    {...srcset(item.img)} 
                    loading="lazy"
                    className= { classes.image }
                  />

                )
              }
        </SwipeableStepper>
        <Typography variant='body2' className={ classes.text }>
            Для организации мероприятия обращайтесь по телефону:<br/><br/>
            <Link href='tel: +78633104110'> 
                    { '+7 863 310 41 10' }
            </Link>
        </Typography>
    </Container>
    </>
  )
}
const images = [
    {
        img: 'images/openSpace3.jpg',
    },
    {
        img: 'images/openSpace2.jpg',
    },
    {
        img: 'images/openSpace.jpg',
    },
];

export const getStaticProps = async () => {
  return {
    props: {},
  }
 }

