import Head from 'next/head';
import { LogoHeader } from '../../components/headers/header.compenent';
import { Footer } from '../../components/footer/footer.component';
import { TopCard } from '../../components/event-page-components/event-page-top-card.component';
import { FreeEventForm } from '../../components/event-page-components/freeBookingForm.component';
import { About } from '../../components/event-page-components/event-page-about.component';
import { EventLineup } from '../../components/event-page-components/event-linup.component';
<<<<<<< HEAD

import { IEvent } from '../../types/event/event.type';
import { GetStaticProps } from 'next'
import { getEventById } from '../../utils/api-utils';
=======
import { VideoPlayer } from '../../components/event-page-components/event-videoPlayer.component';

import { IEvent } from '../../types/event/event.type';
import { fetchActiveEventsPaths, getEventById } from '../../utils/api-utils';
>>>>>>> f51981a9c6f26c62e0c71d92d8654a7e57172852


interface IProps{
  event: IEvent;
}

export default function EventPage({event} : IProps) {
<<<<<<< HEAD
  
=======
>>>>>>> f51981a9c6f26c62e0c71d92d8654a7e57172852
  return (
    <>
      <Head>
        <title>Event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <LogoHeader/>

      <TopCard event={ event }/>

      <About description={ event.description } />

      <EventLineup lineup={ event.lineup }/>

      {event.videoLink && <VideoPlayer videoLink={event.videoLink}/>}

      {event.free && <FreeEventForm/>}

      <Footer />
    </>
  )
}

<<<<<<< HEAD
export const getStaticProps: GetStaticProps = async (context : any) => {
  
  const { id } = context.params;
=======
export const getStaticProps = async (context : any) => {
>>>>>>> f51981a9c6f26c62e0c71d92d8654a7e57172852
  
  const { id } = context.params;
  
  const event : IEvent = await getEventById(id);  

  if(!event || typeof event === undefined)
    return {
      notFound: true
    }
  
  return {
    props: {
      event : event
    }
  }
}
<<<<<<< HEAD
=======

export async function getStaticPaths() {
  
  const paths = await fetchActiveEventsPaths();
  
  return {
    paths: paths,
    fallback: true
  }
}

>>>>>>> f51981a9c6f26c62e0c71d92d8654a7e57172852
