import Head from 'next/head';
import { LogoHeader } from '../../components/headers/header.compenent';
import { Footer } from '../../components/footer/footer.component';
import { TopCard } from '../../components/event-page-components/event-page-top-card.component';
import { FreeEventForm } from '../../components/event-page-components/freeBookingForm.component';
import { About } from '../../components/event-page-components/event-page-about.component';
import { EventLineup } from '../../components/event-page-components/event-linup.component';

import { useState, useEffect } from 'react';
import axios from 'axios';

import { IEvent } from '../../types/event/event.type';
import { GetStaticProps } from 'next'


export default function EventPage({event} : IEvent) {
  
  const [isLoading, setisLoading] = useState(true);
  
  
  return (
    <>
      <Head>
        <title>Event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <LogoHeader/>

      <TopCard/>

      <About description={ event.description } />

      <EventLineup lineup={ event.lineup }/>

      {event.free && <FreeEventForm/>}

      <Footer />
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context : any) => {
  
  const { params } = context;
  
  const { id } = params;
  
  const event : IEvent = await getEventById(id);
  
  if(!event)
    return {
      notFound: true;
    }
  
  return {
    props: {
      event,
    },
  }
}

async function getEventById( id : string) {
  return axios.get(get_event_url.concat( id ))
    .then(res => res.data.event)
    .catch(err => console.error(`Failed fetching event data. ERROR: ${err}`));

}
