import Head from 'next/head';
import { LogoHeader } from '../../components/headers/header.compenent';
import { Footer } from '../../components/footer/footer.component';
import { TopCard } from '../../components/event-page-components/event-page-top-card.component';
import { FreeEventForm } from '../../components/event-page-components/freeBookingForm.component';
import { About } from '../../components/event-page-components/event-page-about.component';
import { EventLineup } from '../../components/event-page-components/event-linup.component';

import { useState, useEffect } from 'react';
import axios from 'axios';
import { IEvent } from '../../types/event/event.type';


export default function EventPage() {
  
  const [eventData, setEventData] = useState(null);
  const [isLoading, setisLoading] = useState(true);
  
  const fetchEventData = (event_id : string) => {
    const event : IEvent = {};  
    axios
      .get(event_url)
      .then(res => event = res.data.event)
      .catch(err => console.error(`Failed fetching event data. ERROR: ${err}`));
    
    setEventData(event);
  }
  
  useEffect(() => {
    if(eventData !== null)
      setIsLoading(false);
  }, [eventData]);
  
  return (
    <>
      <Head>
        <title>Event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { isLoading ? <p>Loading</p> :
       <>
          <LogoHeader/>

          <TopCard/>

          <About/>

          <EventLineup/>

          {event.free && <FreeEventForm/>}

          <Footer />
       </> 
      }
      </>
  )
}
