import Head from 'next/head'
import { AdminHeader } from '../../components/headers/adminHeader.component';
import { AdminMenu } from '../../components/admin-components/main-page/admin-menu.component';


export default function AdminMain () {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AdminHeader />

            <AdminMenu/>
            
        </>
    );
}