import Head from 'next/head'
import { LogoHeader } from '../components/header/header.compenent'
//import MapYand from '../components/contact-page-components/map.component.tsx'
import AboutContact from '../components/contact-page-components/about.component'

export default function Contacts() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>        
        {/**
        @TODO
           Future Structure

                **Contacts**

            <Footer/>
        */}

      <LogoHeader/>

      <AboutContact />

    </>
  )
}
