import Head from 'next/head'
import { LogoHeader } from '../components/header/header.compenent'
import { Footer } from '../components/footer/footer.component'
import { TopCard } from '../components/event-page-components/event-page-top-card.component'
import { FreeEventForm } from '../components/event-page-components/freeBookingForm.component'
import { About } from '../components/event-page-components/event-page-about.component'
import { EventLineup } from '../components/event-page-components/event-linup.component'

export default function EventPage() {
  return (
    <>
      <Head>
        <title>Event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {/**
        @TODO
           Future Structure

            <>
                <Image/>  -  Картинка с карточки
                <h2/> - Event title
                <p/> - Date
                <Badge/> - Pricing
                <Button/> - make reservation button
            </>
            <>
             <p>
                EVENT DESCRIPTION
             </p>
            </>
            <>
             <h3>
                СОСТАВ
             </h3>
            </>
            <>
             <ul>
                <СОСТАВ>
             </ul>
            </>
            <Footer/>
        */}

        <LogoHeader/>

        <TopCard/>

        <About/>

        <EventLineup/>
        
        <FreeEventForm/>

        <Footer />
      </>
  )
}
