import Head from 'next/head'
import { LogoHeader } from '../components/header/header.compenent'

export default function EventPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {/**
        @TODO
           Future Structure

            <>
                <Image/>  -  Картинка с карточки
                <h2/> - Event title
                <p/> - Date
                <Badge/> - Pricing
                <Button/> - make reservation button
            </>
            <>
             <p>
                EVENT DESCRIPTION
             </p>
            </>
            <>
             <h3>
                СОСТАВ
             </h3>
            </>
            <>
             <ul>
                <СОСТАВ>
             </ul>
            </>
            <Footer/>
        */}

      <LogoHeader/>
    </>
  )
}
