import Head from 'next/head';
import { CardSlider } from '../components/cards/slider/card-slider.component';
import { LogoHeader } from '../components/headers/header.compenent';
import { Footer } from '../components/footer/footer.component';
import { BigEventCard } from '../components/cards/bigCard.component';
import { EventCard } from '../components/cards/card.component';
import { SmallEventCard } from '../components/cards/smallCard.component';

import{ SwipeableStepper } from '../components/cards/carousel/carousel.component';

export default function Home() {
  return (
    <>
      <Head>
        <title>Эссе-Дон</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LogoHeader/>

      <SwipeableStepper>
        <BigEventCard/>
        <BigEventCard/>
        <BigEventCard/>
        <BigEventCard/>
        <BigEventCard/>
      </SwipeableStepper>

      <CardSlider>
        <SmallEventCard/>
        <SmallEventCard/>
        <SmallEventCard/>
        <SmallEventCard/>
      </CardSlider>

      <EventCard/>

      <Footer/>

    </>
  )
}
