import Head from 'next/head';
import { LogoHeader } from '../../components/headers/header.compenent';
import { AboutContact } from '../../components/contact-page-components/about.component';
import { ArtistForm } from '../../components/contact-page-components/artist-form.component';
import { MapBox } from '../../components/contact-page-components/map.component';
import { Footer } from '../../components/footer/footer.component';

export default function EventPage() {

  return (
    <>
      <Head>
        <title>Контакты</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
      </Head>

      <LogoHeader/>

      <MapBox/>

      <AboutContact/>

      <ArtistForm/>

      <Footer position='static'/>
    </>
  )
}

export const getServerSideProps = async ({ req, res } : any) => {
    res.setHeader(
    'Cache-Control',
    'public, s-maxage=180000, stale-while-revalidate=59'
  )

  return {
    props: {},
  }
 }

