import Head from 'next/head';
import { LogoHeader } from '../../components/headers/header.compenent';
import { Menu } from '../../components/menu/menu.component';
import { fetchBarItems, fetchKitchenItems } from '../../utils/api-utils';
import { parseMenuItems } from '../../utils/parsing-utils';
import { IMenuItemGroup } from '../../types/menu/menuItem.type';


interface IProps{
  barItems : IMenuItemGroup[];
  kitchenItems : IMenuItemGroup[];
}

export default function MenuPage(props : IProps) {

  console.log(`inside MenuPage:  ${props}`);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LogoHeader/>

      <Menu items={ props }/>
      
    </>
  )
}

export const getStaticProps = async () => {
  const rawBarData = await fetchBarItems();
  const rawKitchenData = await fetchKitchenItems();

  const parsedBarData = parseMenuItems(rawBarData);
  const parsedKitchenData = parseMenuItems(rawKitchenData);

  return {
    props:{
      barItems: parsedBarData,
      kitchenItems: parsedKitchenData,
    }
  }

}