import Head from 'next/head';
import { LogoHeader } from '../../components/headers/header.compenent';
import { Menu } from '../../components/menu/menu.component';
import { Footer } from '../../components/footer/footer.component';

export default function EventPage() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <LogoHeader/>

      <Menu/>

      <Footer/>
      
    </>
  )
}
